### PR TITLE
#168633286 Fix Bug in List Bookmarks

### PR DESCRIPTION
**Pull request by IsaiahRn**
#### What does this PR do?

- Fix Bug in List Bookmarks

#### Description of Task to be completed
- refactor logic on componentDidMount method
- re-style the body paragraph on article bookmarks
#### How should this be manually tested?

1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout  bg-list-bookmarks-168633286
npm install
npm run dev
```
2. Browser to: http://localhost:8080/bookmarks
#### What are the relevant pivotal tracker stories?
[#168633286](https://www.pivotaltracker.com/story/show/168633286)
#### Screenshots (if appropriate)
Screenshot 2019-09-19 17 56 06

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by Hervera — APPROVED** [review]
Implemented well the feedback, ready to be merged.

**Review by elemanhillary-zz — APPROVED** [review]
impressive fix, ready for merge

**Review by niyoceles — APPROVED** [review]
The bug fixed.

**Pull request merged**
