### PR TITLE
#168452394 Bug Fix Users Should Be Able To View Auto-updated Following 

### PR DESCRIPTION
**Pull request by niyoceles**
#### What does this PR do?
- Enable user to view auto-updated
#### Description of Task to be completed
- Ensure user view auto-updated following 

#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout bg-view-auto-updated-following-168452394
configure .env file 

npm install

npm run dev
```
- Browser to: `http://localhost:8080/user-profile/{username}`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168452394](https://www.pivotaltracker.com/story/show/168452394)

#### Screenshots (if appropriate)
- Follow & Unfollow page
Screen Shot 2019-09-11 at 10 39 11

- view my followers & my following
Screen Shot 2019-09-11 at 10 38 28

Screen Shot 2019-09-13 at 13 47 23

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by kodek-sleuth — CHANGES_REQUESTED** [review]
As a user, I want to be able to see the current following and followers of a another user, I have failed to see the follower count of someone increase when I follow/unfollow them

**Review by kodek-sleuth — DISMISSED** [review]

**Review by Hervera — DISMISSED** [review]
Nice improvement, the following count is updated automatically.

**Review by elemanhillary-zz — DISMISSED** [review]
@niyoceles good work

**Review by kodek-sleuth — DISMISSED** [review]

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by Hervera — DISMISSED** [review]
The bug is fixed, it is ready to be merged.

**Review by kodek-sleuth — CHANGES_REQUESTED** [review]
Apply a border-radius to all images in the pop of followers

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Review by kodek-sleuth — APPROVED** [review]

**Review by Hervera — APPROVED** [review]

**Pull request merged**
