### PR TITLE
#166789952 Users Should Be Presented with a Reset Password Link

### PR DESCRIPTION
**Pull request by niyoceles**
#### What does this PR do?
-  Add reset password functionality
- Write tests
#### Description of Task to be completed
- Enable a user to  get a link for resetting a password

#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ft-present-reset-password-166789952
configure .env file `APP_URL_BACKEND and CRYPTO_PASSWORD` values

npm install

npm run dev
```
- Browser to: `http://localhost:8080/reset-password`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166789952](https://www.pivotaltracker.com/story/show/166789952)
#### Screenshots (if appropriate)
- Validation
Screen Shot 2019-09-01 at 18 40 46
Screen Shot 2019-09-01 at 18 42 04
Screen Shot 2019-09-01 at 18 43 07

- Successfully reset password
Screen Shot 2019-09-03 at 08 18 10

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
after showing the toast to a user that you have emailed him/her the reset link, the toast should be static on the page, put there a timeout to show and hide the toast

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
ready for merge

**Review by Hervera — APPROVED** [review]
Ready to be merged

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Review by kodek-sleuth — APPROVED** [review]

**Pull request merged**
