### PR TITLE
#167972452 Setup Project Structure

### PR DESCRIPTION
**Pull request by kodek-sleuth**
#### What does this PR do?
Should folder structure 
#### Description of Task to be completed
- Create a constants folder that will store global project constants
- Create Layout and Views Folder for respective components
#### How should this be manually tested?
```
Run the following commands in your terminal after cloning the project
1. cd ah-92explorers-frontend
2. git checkout ch-setup-folder-structure-167972452
3. `npm i` to install all dependencies 
4. `npm run dev` and navigate to localhost:8080
```
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#167972452](https://www.pivotaltracker.com/story/show/167972452)
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by IsaiahRn — APPROVED** [review]

**Review by niyoceles — APPROVED** [review]
ready to be merged

**Review by Hervera — CHANGES_REQUESTED** [review]
You have more than one commit

**Review by niyoceles — APPROVED** [review]

**Review by niyoceles — APPROVED** [review]
This PR is ready to be merged

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
your routes are not working they display a 404 error code since the home route is protected I expect it to redirect me to the login page as per your implementation, kindly fix the issue. Thanks

**Comment by kipropbrian** [comment]
Your description is lacking, what folders have you changed. How was it before and how is it now. Have you changed the redux folder structure?

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Review by niyoceles — APPROVED** [review]
Good work

**Review by IsaiahRn — APPROVED** [review]
After reviewing this PR, I am confirming that it is ready to merged!

**Pull request merged**
