### PR TITLE
Users Should Be Able To Read And Delete An Article

### PR DESCRIPTION
**Pull request by elemanhillary-zz**
#### What does this PR do?
- adds read and delete an article functionalities

#### Description of Task to be completed
- enables both authenticated and non-authenticated user to read article
- enables article author to delete and update article

#### How should this be manually tested?
```bash
git clone https://github.com/andela/ah-92explorers-frontend.git
git checkout ft-read-delete-article-167971932
npm install
npm run dev
```
- Before `npm run dev` add to your .env file:
```
APP_URL_BACKEND=
CRYPTO_PASSWORD=20562d21740418a343cb7e4f619ef914(should not change)
CLOUDINARY_URL=
DEFAULT_IMAGE=
```
- Navigate to `localhost:<port>/article/:<article-slug>`

#### Any background context you want to provide?
- None

#### What are the relevant pivotal tracker stories?
[#167971932](https://www.pivotaltracker.com/story/show/167971932)

#### Screenshots (if appropriate)
Imgur

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by niyoceles — APPROVED** [review]

**Review by niyoceles — CHANGES_REQUESTED** [review]
@elemanhillary the body of an article must be justified and you can also add the margin-right. (on the mobile devices)

**Review by Hervera — DISMISSED** [review]
Ready to be merged

**Review by kodek-sleuth — CHANGES_REQUESTED** [review]
The css styling of the homepage is broken. Kindly fix this.
Screen Shot 2019-09-04 at 10 53 01
That is the actual styling on the homepage
Screen Shot 2019-09-04 at 10 43 46
This is your styling

**Review by niyoceles — DISMISSED** [review]
It can be merged.

**Review by kodek-sleuth — APPROVED** [review]

**Review by Hervera — APPROVED** [review]
Ready to be merged

**Review by niyoceles — APPROVED** [review]
It can be merged

**Pull request merged**
