### PR TITLE
#166789975 Users Should Be Able To See Their Reading Stats

### PR DESCRIPTION
**Pull request by niyoceles**
#### What does this PR do?
- Enable user to view auto-updated
#### Description of Task to be completed
- Ensure user view auto-updated following 

#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ft-reading-stats-166789975
configure .env file 

npm install

npm run dev
```
- Browser to: `http://localhost:8080/articles/{slug}`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166789975](https://www.pivotaltracker.com/story/show/166789975)

#### Screenshots (if appropriate)
- View my stats
click on Stats button
Screen Shot 2019-09-15 at 20 01 04

Screen Shot 2019-09-18 at 09 50 45

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
Hey @niyoceles this PR's code breaks another functionality kindly fix that
```javascript
likes.forEach((like)=>{})
```
Breaks when there are 2 more likes
ezgif com-video-to-gif (2)

**Review by kodek-sleuth — CHANGES_REQUESTED** [review]
I failed to navigate to any article as the page kept on breaking and kindly add a loader with an elapsed time to always tell the user that nothing has come after all

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by kodek-sleuth — CHANGES_REQUESTED** [review]
Please resolve those conflicts before requesting for reviewers

**Review by kodek-sleuth — CHANGES_REQUESTED** [review]
The grammar in the column for readings is incorrect

**Review by Hervera — APPROVED** [review]
I have liked the logic you have given to this feature, to start counting reading stats when the user is already logged in.

**Review by kodek-sleuth — APPROVED** [review]

**Review by IsaiahRn — APPROVED** [review]
It can be merged

**Pull request merged**
