### PR TITLE
#166789944 Setup An Empty React Project

### PR DESCRIPTION
**Pull request by niyoceles**
#### What does this PR do?
React project configuration
#### Description of Task to be completed
- Configure react using webpack
- Configure babel
- Configure airbnb linting
#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ch-setup-react-project-166789944
npm install
npm run start
```
#### What are the relevant pivotal tracker stories?
[#166789944](https://www.pivotaltracker.com/story/show/166789944)

#### Screenshots (if appropriate)
Screen Shot 2019-08-13 at 22 19 05

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by Hervera — APPROVED** [review]
Ready to be merged

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
add `historyApiFallback` in your `webpack` config file, e.g when you navigate through routes and you want to just type in the route name in your browser it will fail when you want to navigate to the previous route most times it will fail. kindly add that.

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
you are also missing the resolve extensions object for `.js` and `.jsx` to enable webpack and eslint recognize the `.jsx` syntax in `js` files

**Review by IsaiahRn — APPROVED** [review]
This PR is ready to be merged!

**Comment by niyoceles** [comment]
> add `historyApiFallback` in your `webpack` config file, e.g when you navigate through routes and you want to just type in the route name in your browser it will fail when you want to navigate to the previous route most times it will fail. kindly add that.

Actually, that is a good idea.

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
ready for merge

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Pull request merged**
