### PR TITLE
#166789957 Users should be able to rate articles

### PR DESCRIPTION
**Pull request by IsaiahRn**
#### What does this PR do?

- Users should be able to rate articles

#### Description of Task to be completed

- Add rating component

- Connect rating to article component

- Add rating functionality

- Add tests

#### How should this be manually tested?

1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ft-rating-articles-166789957
npm install
npm run dev and navigate to localhost:8080/article/:articleSlug/ to rate an article
```
#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- [#166789957](https://www.pivotaltracker.com/story/show/166789957)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by kodek-sleuth — DISMISSED** [review]
I failed to rate any article, The rate icon does not appear and when I click on rates I think it redirects to a 404. I think it would be best to actually bring the average ratings if their there otherwise not. Please fix this issue so that I can be able to actually rate an article.

**Comment by IsaiahRn** [comment]
> I failed to rate any article, The rate icon does not appear and when I click on rates I think it redirects to a 404. I think it would be best to actually bring the average ratings if their there otherwise not. Please fix this issue so that I can be able to actually rate an article.

I really don't know what might be that issue because I am able to rate, view average and view ratings of a particular article.

**Review by niyoceles — DISMISSED** [review]
Good work, I am impressed about this work, It can be merged.

**Review by Hervera — DISMISSED** [review]
Good work

**Review by niyoceles — APPROVED** [review]
It can be merged

**Review by Hervera — APPROVED** [review]
Changes well implemented

**Review by kodek-sleuth — APPROVED** [review]

**Pull request merged**
