### PR TITLE
#166789970 List Bookmarked Articles

### PR DESCRIPTION
**Pull request by IsaiahRn**
#### What does this PR do?

- Users should view their bookmarked articles

#### Description of Task to be completed

- Authenticated user will be able to see the list of his bookmarks

- Add tests for the feature

#### How should this be manually tested?

1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ft-list-bookmarks-166789970
npm install
npm run dev
```

2. Browser to: http://localhost:8080/bookmarks

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?
[#166789970](https://www.pivotaltracker.com/story/show/166789970)
#### Screenshots (if appropriate)
Screenshot 2019-09-18 16 39 48

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by kodek-sleuth — DISMISSED** [review]
This is nice work but after using thorough using of this system from the users eyes, I have come up with some feedback.
However much am able to bookmark an article, I as a user expect UI change like filling of the Bookmark Icon.

I believe that as we had discussed, there is no need for alert messages rather UI changes that the users are already used to.

I should expect a message telling me no bookmarks exist is my catalogue rather a blank page with only bookmark as a title. Something like
```
Bookmarks
Bookmarked article will show here is precise
```

The delete button does not function and am unable to reverse a bookmark rather delete a bookmark

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by niyoceles — DISMISSED** [review]
List of the bookmarked article is working, so it can be merged

**Review by Hervera — DISMISSED** [review]
I would prefer the trash icon to unbookmark an article to be a bookmark icon. But that's a good work, the funtionalities of listing bookmark and unbookmark work very well.

**Review by Hervera — APPROVED** [review]
Feedback is well implemented

**Pull request merged**
