### PR TITLE
#166789962  Article tags should be present in all relevant views

### PR DESCRIPTION
**Pull request by kodek-sleuth**
#### What does this PR do?
- Should enable a user to enter tags as well as see articles in specific tags
#### Description of Task to be completed
- Setup Methods for both previewing and entering tags
#### How should this be manually tested?
```
1. cd ah-92explorers-frontend
2. git checkout ft-group-articles-by-tags-166789962
3. npm i to install all dependencies 
4. npm run dev` and navigate to localhost:8080
```
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166789962](https://www.pivotaltracker.com/story/show/166789962)
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — APPROVED** [review]
kindly fix tests

**Review by elemanhillary-zz — DISMISSED** [review]
kindly fix tests

**Review by IsaiahRn — DISMISSED** [review]

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by IsaiahRn — DISMISSED** [review]

**Review by Hervera — DISMISSED** [review]
Creating Tags and viewing them work very well. Ready to be merged

**Review by niyoceles — APPROVED** [review]
It can be merged.

**Review by Hervera — APPROVED** [review]

**Pull request merged**
