### PR TITLE
#166789963 Users Should Be Able To Share Articles on Social Media and Via Email

### PR DESCRIPTION
**Pull request by Hervera**
#### What does this PR do?
Enables users to share articles on social media and via email

#### Description of Task to be completed
    - add share icons component
    - add CSS stylesheet
    - add share functionalities
    - add tests

#### How should this be manually tested?
1. Run the following commands in the terminal
```
Clone the project
 cd ah-92explorers-frontend
 git checkout ft-share-articles-166789963
`npm i` to install all dependencies 
`npm run dev` and navigate to localhost:8080/article/:articleSlug/ to share an article
```

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166789963](https://www.pivotaltracker.com/story/show/166789963)

#### Screenshots (if appropriate)
Screen Shot 2019-09-09 at 00 56 23

Screen Shot 2019-09-09 at 01 27 47

Screen Shot 2019-09-09 at 01 28 05

Screen Shot 2019-09-09 at 01 28 36

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — DISMISSED** [review]
good work Herve, its ready to be merged

**Review by IsaiahRn — DISMISSED** [review]
This feature was well implemented, it can be merged!

**Review by IsaiahRn — DISMISSED** [review]
I approve this PR because a user is able to share their articles.

**Review by niyoceles — DISMISSED** [review]
good job.

**Review by elemanhillary-zz — DISMISSED** [review]
functionality working.

**Review by kodek-sleuth — DISMISSED** [review]

**Review by IsaiahRn — DISMISSED** [review]

**Review by IsaiahRn — APPROVED** [review]

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Review by niyoceles — APPROVED** [review]
It can be merge

**Pull request merged**
