### PR TITLE
#166789946 Setup End to End and Unit Tests

### PR DESCRIPTION
**Pull request by IsaiahRn**
#### What does this PR do?

- Write end to end tests

- Write unit tests

#### Description of Task to be completed
- setup cypress

- configure jest

- setup enzyme

#### How should this be manually tested?

- Run the following commands in the terminal

1. Run End to End Tests

```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ch-setup-e2e-tests-166789946
npm install
npm run cypress
or
npm run cy:open
```

2. Run Unit Tests

```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ch-setup-e2e-tests-166789946
npm install
npm test
```
 
#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- [#166789946](https://www.pivotaltracker.com/story/show/166789946)

#### Screenshots (if appropriate)

- Passing Unit Test with Jest

Screenshot 2019-08-14 16 08 27

- Passing End To End Tests with Cypress in `Browser`

Screenshot 2019-08-14 18 40 41

- Passing End To End Tests with Cypress in `Terminal`

Screenshot 2019-08-16 12 12 13
Screenshot 2019-08-16 12 12 25

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by Hervera — APPROVED** [review]
Ready to be merged

**Review by kodek-sleuth — APPROVED** [review]
This PR is ready to be merged

**Review by niyoceles — APPROVED** [review]
Ready to be merged.

**Comment by kipropbrian** [comment]
Make sure Cypress can run on terminal

**Pull request merged**
