### PR TITLE
#166789965 User Should Be Able to View Notifications:

### PR DESCRIPTION
**Pull request by elemanhillary-zz**
#### What does this PR do?
- adds view notifications functionality

#### Description of Task to be completed
- enable the user to view notifications

#### How should this be manually tested?
```bash
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ft-notifications-166789965
npm i
npm run dev
```
- navigate to browser `http://localhost:8080/article/<article-slug>`
- click notification icon

#### Any background context you want to provide?
- None

#### What are the relevant pivotal tracker stories?
[#166789965](https://www.pivotaltracker.com/story/show/166789965)
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by niyoceles — DISMISSED** [review]
This PR is ready to be merged

**Review by Hervera — DISMISSED** [review]
Impressive work! I can see new notifications in navbar icon when someone i follow write an article or a comment

**Review by IsaiahRn — DISMISSED** [review]
This PR can be merged

**Review by Hervera — DISMISSED** [review]

**Review by niyoceles — DISMISSED** [review]
View notification can be merged.

**Review by IsaiahRn — DISMISSED** [review]
A user can view notifications, so it is ready for merge!

**Review by Hervera — DISMISSED** [review]

**Review by niyoceles — DISMISSED** [review]
Ready for merge

**Review by niyoceles — APPROVED** [review]
Good job

**Review by Hervera — APPROVED** [review]

**Review by IsaiahRn — APPROVED** [review]
This PR can be merged!

**Pull request merged**
