### PR TITLE
#167941138 Deploy Application To Heroku

### PR DESCRIPTION
**Pull request by Hervera**
#### What does this PR do?
Deploys frontend application to Heroku

#### Description of Task to be completed
- add a server file
- setup Heroku
- add a command to start the app after deployment

#### How should this be manually tested?
Go to this URL:  [https://ah-92explorers-frontend.herokuapp.com/](https://ah-92explorers-frontend.herokuapp.com/)

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#167941138](https://www.pivotaltracker.com/story/show/167941138)

#### Screenshots (if appropriate)
Screen Shot 2019-08-16 at 18 38 08

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Comment by kipropbrian** [comment]
Could you update the readme file with the heroku link.

**Review by IsaiahRn — APPROVED** [review]

**Comment by Hervera** [comment]
> Yes, Let me update the readme file

**Comment by Hervera** [comment]
> Could you update the readme file with the heroku link.

> Readme file is updated with the heroku link

**Review by niyoceles — APPROVED** [review]

**Review by kodek-sleuth — CHANGES_REQUESTED** [review]
There is a way to deploy an App to Heroku without setting up an Express Server. Installing a package `serve` which will run the build refer to `https://www.npmjs.com/package/serve`

**Comment by elemanhillary-zz** [comment]
> There is a way to deploy an App to Heroku without setting up an Express Server. Installing a package `serve` which will run the build refer to `https://www.npmjs.com/package/serve`

**Review by niyoceles — APPROVED** [review]

**Review by kodek-sleuth — APPROVED** [review]
This PR is ready to be merged

**Pull request merged**
