### PR TITLE
#166789964 Users Should Be Able to Follow Each Other

### PR DESCRIPTION
**Pull request by niyoceles**
#### What does this PR do?
- Enable user to follow each other
#### Description of Task to be completed
- Ensure user to follow each other
- Add tests
- Follow and unfollow functionality
- Enable to view followers & following
#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-frontend.git
cd ah-92explorers-frontend
git checkout ft-follow-each-other-166789964
configure .env file 

npm install

npm run dev
```
- Browser to: `http://localhost:8080/user-profile/{username}`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166789964](https://www.pivotaltracker.com/story/show/166789964)

#### Screenshots (if appropriate)
- Follow & Unfollow page
Screen Shot 2019-09-11 at 10 39 11

- view my followers & my following
Screen Shot 2019-09-11 at 10 38 28

Screen Shot 2019-09-12 at 10 23 35

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — DISMISSED** [review]
follow works as expected

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
i think screenshots are important here as evidence to prove the work. kindly edit your PR body to contain a screenshot

**Review by elemanhillary-zz — DISMISSED** [review]
functionality as stated is perfectly working and can be merged

**Review by Hervera — DISMISSED** [review]
Well implemented but there is still a way we can make it better by showing also the number of followers and following with the follow button on the same page.

**Review by IsaiahRn — DISMISSED** [review]
This PR is ready for merge, well done @niyoceles

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by kodek-sleuth — CHANGES_REQUESTED** [review]
As a user, I should not see an empty card of followers pop up when I hover over if I have no followers. The social media buttons on that page, don't also work

**Review by Hervera — APPROVED** [review]
Well done, I can easily see and test the functionality of following and unfollowing buttons on each user profile.

**Review by kodek-sleuth — APPROVED** [review]

**Review by elemanhillary-zz — APPROVED** [review]
its ready for merge

**Review by IsaiahRn — APPROVED** [review]

**Pull request merged**
